name: fly.io deploy dev

on:
  push:
    branches: [dev]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_DEV }}

jobs:
  deploy:
    name: deploy dev

    runs-on: ubuntu-latest

    environment: development

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun i --ignore-scripts
      - run: bun lint

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --detach --no-cache --config fly-dev.toml
